-name: variables from inventory
hosts: local
connection: local
tasks:
  -name: print course info
  ansible.builtin.debug:
  msg: " hello, welcome to {{ course }} course, the duration is {{ duration }} and trainer is {{ trainer }}"
