-name: variables from inventory
hosts: frontend
tasks:
  -name: print course info from frontend host
  ansible.builtin.debug:
  msg: "Hello, welocme to {{ course }} course, the duration is {{ duration }}, the trainer is {{ trainer }}"
